// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	artifact "github.com/harness/gitness/registry/app/api/openapi/contracts/artifact"

	json "encoding/json"

	mock "github.com/stretchr/testify/mock"

	types "github.com/harness/gitness/registry/types"
)

// ArtifactRepository is an autogenerated mock type for the ArtifactRepository type
type ArtifactRepository struct {
	mock.Mock
}

// GetByUUID provides a mock function with given fields: ctx, uuid
func (_m *ArtifactRepository) GetByUUID(ctx context.Context, uuid string) (*types.Artifact, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetByUUID")
	}

	var r0 *types.Artifact
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*types.Artifact, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *types.Artifact); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Artifact)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, id
func (_m *ArtifactRepository) Get(ctx context.Context, id int64) (*types.Artifact, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *types.Artifact
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*types.Artifact, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *types.Artifact); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Artifact)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Count provides a mock function with given fields: ctx, softDeleteFilter
func (_m *ArtifactRepository) Count(ctx context.Context, opts ...types.QueryOption) (int64, error) {
	ret := _m.Called(ctx, softDeleteFilter)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.SoftDeleteFilter) (int64, error)); ok {
		return rf(ctx, softDeleteFilter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.SoftDeleteFilter) int64); ok {
		r0 = rf(ctx, softDeleteFilter)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.SoftDeleteFilter) error); ok {
		r1 = rf(ctx, softDeleteFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountAllArtifactsByParentID provides a mock function with given fields: ctx, parentID, registryIDs, search, latestVersion, packageTypes, softDeleteFilter
func (_m *ArtifactRepository) CountAllArtifactsByParentID(ctx context.Context, parentID int64, registryIDs *[]string, search string, latestVersion bool, packageTypes []string, opts ...types.QueryOption) (int64, error) {
	ret := _m.Called(ctx, parentID, registryIDs, search, latestVersion, packageTypes, softDeleteFilter)

	if len(ret) == 0 {
		panic("no return value specified for CountAllArtifactsByParentID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *[]string, string, bool, []string, types.SoftDeleteFilter) (int64, error)); ok {
		return rf(ctx, parentID, registryIDs, search, latestVersion, packageTypes, softDeleteFilter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *[]string, string, bool, []string, types.SoftDeleteFilter) int64); ok {
		r0 = rf(ctx, parentID, registryIDs, search, latestVersion, packageTypes, softDeleteFilter)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *[]string, string, bool, []string, types.SoftDeleteFilter) error); ok {
		r1 = rf(ctx, parentID, registryIDs, search, latestVersion, packageTypes, softDeleteFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountAllVersionsByRepoAndImage provides a mock function with given fields: ctx, parentID, repoKey, image, search, artifactType, softDeleteFilter
func (_m *ArtifactRepository) CountAllVersionsByRepoAndImage(ctx context.Context, parentID int64, repoKey string, image string, search string, artifactType *artifact.ArtifactType, opts ...types.QueryOption) (int64, error) {
	ret := _m.Called(ctx, parentID, repoKey, image, search, artifactType, softDeleteFilter)

	if len(ret) == 0 {
		panic("no return value specified for CountAllVersionsByRepoAndImage")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, string, *artifact.ArtifactType, types.SoftDeleteFilter) (int64, error)); ok {
		return rf(ctx, parentID, repoKey, image, search, artifactType, softDeleteFilter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, string, *artifact.ArtifactType, types.SoftDeleteFilter) int64); ok {
		r0 = rf(ctx, parentID, repoKey, image, search, artifactType, softDeleteFilter)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, string, string, *artifact.ArtifactType, types.SoftDeleteFilter) error); ok {
		r1 = rf(ctx, parentID, repoKey, image, search, artifactType, softDeleteFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountArtifactsByRepo provides a mock function with given fields: ctx, parentID, repoKey, search, labels, artifactType, softDeleteFilter
func (_m *ArtifactRepository) CountArtifactsByRepo(ctx context.Context, parentID int64, repoKey string, search string, labels []string, artifactType *artifact.ArtifactType, opts ...types.QueryOption) (int64, error) {
	ret := _m.Called(ctx, parentID, repoKey, search, labels, artifactType, softDeleteFilter)

	if len(ret) == 0 {
		panic("no return value specified for CountArtifactsByRepo")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, []string, *artifact.ArtifactType, types.SoftDeleteFilter) (int64, error)); ok {
		return rf(ctx, parentID, repoKey, search, labels, artifactType, softDeleteFilter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, []string, *artifact.ArtifactType, types.SoftDeleteFilter) int64); ok {
		r0 = rf(ctx, parentID, repoKey, search, labels, artifactType, softDeleteFilter)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, string, []string, *artifact.ArtifactType, types.SoftDeleteFilter) error); ok {
		r1 = rf(ctx, parentID, repoKey, search, labels, artifactType, softDeleteFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountByImageName provides a mock function with given fields: ctx, regID, name, softDeleteFilter
func (_m *ArtifactRepository) CountByImageName(ctx context.Context, regID int64, name string, opts ...types.QueryOption) (int64, error) {
	ret := _m.Called(ctx, regID, name, softDeleteFilter)

	if len(ret) == 0 {
		panic("no return value specified for CountByImageName")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, types.SoftDeleteFilter) (int64, error)); ok {
		return rf(ctx, regID, name, softDeleteFilter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, types.SoftDeleteFilter) int64); ok {
		r0 = rf(ctx, regID, name, softDeleteFilter)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, types.SoftDeleteFilter) error); ok {
		r1 = rf(ctx, regID, name, softDeleteFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountLatestByName provides a mock function with given fields: ctx, regID, name, softDeleteFilter
func (_m *ArtifactRepository) CountLatestByName(ctx context.Context, regID int64, name string, opts ...types.QueryOption) (int64, error) {
	ret := _m.Called(ctx, regID, name, softDeleteFilter)

	if len(ret) == 0 {
		panic("no return value specified for CountLatestByName")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, types.SoftDeleteFilter) (int64, error)); ok {
		return rf(ctx, regID, name, softDeleteFilter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, types.SoftDeleteFilter) int64); ok {
		r0 = rf(ctx, regID, name, softDeleteFilter)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, types.SoftDeleteFilter) error); ok {
		r1 = rf(ctx, regID, name, softDeleteFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateOrUpdate provides a mock function with given fields: ctx, _a1
func (_m *ArtifactRepository) CreateOrUpdate(ctx context.Context, _a1 *types.Artifact) (int64, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdate")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.Artifact) (int64, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *types.Artifact) int64); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *types.Artifact) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteByImageNameAndRegistryID provides a mock function with given fields: ctx, regID, image
func (_m *ArtifactRepository) DeleteByImageNameAndRegistryID(ctx context.Context, regID int64, image string) error {
	ret := _m.Called(ctx, regID, image)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByImageNameAndRegistryID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, regID, image)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByVersionAndImageName provides a mock function with given fields: ctx, image, version, regID
func (_m *ArtifactRepository) DeleteByVersionAndImageName(ctx context.Context, image string, version string, regID int64) error {
	ret := _m.Called(ctx, image, version, regID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByVersionAndImageName")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) error); ok {
		r0 = rf(ctx, image, version, regID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DuplicateArtifact provides a mock function with given fields: ctx, sourceArtifact, targetImageID
func (_m *ArtifactRepository) DuplicateArtifact(ctx context.Context, sourceArtifact *types.Artifact, targetImageID int64) (*types.Artifact, error) {
	ret := _m.Called(ctx, sourceArtifact, targetImageID)

	if len(ret) == 0 {
		panic("no return value specified for DuplicateArtifact")
	}

	var r0 *types.Artifact
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.Artifact, int64) (*types.Artifact, error)); ok {
		return rf(ctx, sourceArtifact, targetImageID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *types.Artifact, int64) *types.Artifact); ok {
		r0 = rf(ctx, sourceArtifact, targetImageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Artifact)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *types.Artifact, int64) error); ok {
		r1 = rf(ctx, sourceArtifact, targetImageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllArtifactsByParentID provides a mock function with given fields: ctx, parentID, registryIDs, search, latestVersion, packageTypes, limit, offset, softDeleteFilter
func (_m *ArtifactRepository) GetAllArtifactsByParentID(ctx context.Context, parentID int64, registryIDs *[]string, search string, latestVersion bool, packageTypes []string, limit int, offset int, opts ...types.QueryOption) (*[]types.ArtifactMetadata, error) {
	ret := _m.Called(ctx, parentID, registryIDs, search, latestVersion, packageTypes, limit, offset, softDeleteFilter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllArtifactsByParentID")
	}

	var r0 *[]types.ArtifactMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *[]string, string, bool, []string, int, int, types.SoftDeleteFilter) (*[]types.ArtifactMetadata, error)); ok {
		return rf(ctx, parentID, registryIDs, search, latestVersion, packageTypes, limit, offset, softDeleteFilter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *[]string, string, bool, []string, int, int, types.SoftDeleteFilter) *[]types.ArtifactMetadata); ok {
		r0 = rf(ctx, parentID, registryIDs, search, latestVersion, packageTypes, limit, offset, softDeleteFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]types.ArtifactMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *[]string, string, bool, []string, int, int, types.SoftDeleteFilter) error); ok {
		r1 = rf(ctx, parentID, registryIDs, search, latestVersion, packageTypes, limit, offset, softDeleteFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllArtifactsByRepo provides a mock function with given fields: ctx, registryID, batchSize, artifactID
func (_m *ArtifactRepository) GetAllArtifactsByRepo(ctx context.Context, registryID int64, batchSize int, artifactID int64) (*[]types.ArtifactMetadata, error) {
	ret := _m.Called(ctx, registryID, batchSize, artifactID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllArtifactsByRepo")
	}

	var r0 *[]types.ArtifactMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int64) (*[]types.ArtifactMetadata, error)); ok {
		return rf(ctx, registryID, batchSize, artifactID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int64) *[]types.ArtifactMetadata); ok {
		r0 = rf(ctx, registryID, batchSize, artifactID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]types.ArtifactMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, int64) error); ok {
		r1 = rf(ctx, registryID, batchSize, artifactID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllVersionsByRepoAndImage provides a mock function with given fields: ctx, id, image, field, order, limit, offset, term, artifactType, softDeleteFilter
func (_m *ArtifactRepository) GetAllVersionsByRepoAndImage(ctx context.Context, id int64, image string, field string, order string, limit int, offset int, term string, artifactType *artifact.ArtifactType, opts ...types.QueryOption) (*[]types.NonOCIArtifactMetadata, error) {
	ret := _m.Called(ctx, id, image, field, order, limit, offset, term, artifactType, softDeleteFilter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllVersionsByRepoAndImage")
	}

	var r0 *[]types.NonOCIArtifactMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, string, int, int, string, *artifact.ArtifactType, types.SoftDeleteFilter) (*[]types.NonOCIArtifactMetadata, error)); ok {
		return rf(ctx, id, image, field, order, limit, offset, term, artifactType, softDeleteFilter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, string, int, int, string, *artifact.ArtifactType, types.SoftDeleteFilter) *[]types.NonOCIArtifactMetadata); ok {
		r0 = rf(ctx, id, image, field, order, limit, offset, term, artifactType, softDeleteFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]types.NonOCIArtifactMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, string, string, int, int, string, *artifact.ArtifactType, types.SoftDeleteFilter) error); ok {
		r1 = rf(ctx, id, image, field, order, limit, offset, term, artifactType, softDeleteFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetArtifactMetadata provides a mock function with given fields: ctx, id, identifier, image, version, artifactType, softDeleteFilter
func (_m *ArtifactRepository) GetArtifactMetadata(ctx context.Context, id int64, identifier string, image string, version string, artifactType *artifact.ArtifactType, opts ...types.QueryOption) (*types.ArtifactMetadata, error) {
	ret := _m.Called(ctx, id, identifier, image, version, artifactType, softDeleteFilter)

	if len(ret) == 0 {
		panic("no return value specified for GetArtifactMetadata")
	}

	var r0 *types.ArtifactMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, string, *artifact.ArtifactType, types.SoftDeleteFilter) (*types.ArtifactMetadata, error)); ok {
		return rf(ctx, id, identifier, image, version, artifactType, softDeleteFilter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, string, *artifact.ArtifactType, types.SoftDeleteFilter) *types.ArtifactMetadata); ok {
		r0 = rf(ctx, id, identifier, image, version, artifactType, softDeleteFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ArtifactMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, string, string, *artifact.ArtifactType, types.SoftDeleteFilter) error); ok {
		r1 = rf(ctx, id, identifier, image, version, artifactType, softDeleteFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetArtifactsByRepo provides a mock function with given fields: ctx, parentID, repoKey, search, labels, latestVersion, limit, offset, sortByField, sortByOrder, artifactType, softDeleteFilter
func (_m *ArtifactRepository) GetArtifactsByRepo(ctx context.Context, parentID int64, repoKey string, search string, labels []string, latestVersion bool, limit int, offset int, sortByField string, sortByOrder string, artifactType *artifact.ArtifactType, opts ...types.QueryOption) (*[]types.ArtifactMetadata, error) {
	ret := _m.Called(ctx, parentID, repoKey, search, labels, latestVersion, limit, offset, sortByField, sortByOrder, artifactType, softDeleteFilter)

	if len(ret) == 0 {
		panic("no return value specified for GetArtifactsByRepo")
	}

	var r0 *[]types.ArtifactMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, []string, bool, int, int, string, string, *artifact.ArtifactType, types.SoftDeleteFilter) (*[]types.ArtifactMetadata, error)); ok {
		return rf(ctx, parentID, repoKey, search, labels, latestVersion, limit, offset, sortByField, sortByOrder, artifactType, softDeleteFilter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, []string, bool, int, int, string, string, *artifact.ArtifactType, types.SoftDeleteFilter) *[]types.ArtifactMetadata); ok {
		r0 = rf(ctx, parentID, repoKey, search, labels, latestVersion, limit, offset, sortByField, sortByOrder, artifactType, softDeleteFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]types.ArtifactMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, string, []string, bool, int, int, string, string, *artifact.ArtifactType, types.SoftDeleteFilter) error); ok {
		r1 = rf(ctx, parentID, repoKey, search, labels, latestVersion, limit, offset, sortByField, sortByOrder, artifactType, softDeleteFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetArtifactsByRepoAndImageBatch provides a mock function with given fields: ctx, registryID, imageName, batchSize, artifactID
func (_m *ArtifactRepository) GetArtifactsByRepoAndImageBatch(ctx context.Context, registryID int64, imageName string, batchSize int, artifactID int64) (*[]types.ArtifactMetadata, error) {
	ret := _m.Called(ctx, registryID, imageName, batchSize, artifactID)

	if len(ret) == 0 {
		panic("no return value specified for GetArtifactsByRepoAndImageBatch")
	}

	var r0 *[]types.ArtifactMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int, int64) (*[]types.ArtifactMetadata, error)); ok {
		return rf(ctx, registryID, imageName, batchSize, artifactID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int, int64) *[]types.ArtifactMetadata); ok {
		r0 = rf(ctx, registryID, imageName, batchSize, artifactID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]types.ArtifactMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, int, int64) error); ok {
		r1 = rf(ctx, registryID, imageName, batchSize, artifactID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByName provides a mock function with given fields: ctx, imageID, version, includeSoftDeleted
func (_m *ArtifactRepository) GetByName(ctx context.Context, imageID int64, version string, includeSoftDeleted types.SoftDeleteFilter) (*types.Artifact, error) {
	ret := _m.Called(ctx, imageID, version, includeSoftDeleted)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *types.Artifact
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, types.SoftDeleteFilter) (*types.Artifact, error)); ok {
		return rf(ctx, imageID, version, includeSoftDeleted)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, types.SoftDeleteFilter) *types.Artifact); ok {
		r0 = rf(ctx, imageID, version, includeSoftDeleted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Artifact)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, types.SoftDeleteFilter) error); ok {
		r1 = rf(ctx, imageID, version, includeSoftDeleted)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByRegistryIDAndImage provides a mock function with given fields: ctx, registryID, image, softDeleteFilter
func (_m *ArtifactRepository) GetByRegistryIDAndImage(ctx context.Context, registryID int64, image string, opts ...types.QueryOption) (*[]types.Artifact, error) {
	ret := _m.Called(ctx, registryID, image, softDeleteFilter)

	if len(ret) == 0 {
		panic("no return value specified for GetByRegistryIDAndImage")
	}

	var r0 *[]types.Artifact
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, types.SoftDeleteFilter) (*[]types.Artifact, error)); ok {
		return rf(ctx, registryID, image, softDeleteFilter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, types.SoftDeleteFilter) *[]types.Artifact); ok {
		r0 = rf(ctx, registryID, image, softDeleteFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]types.Artifact)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, types.SoftDeleteFilter) error); ok {
		r1 = rf(ctx, registryID, image, softDeleteFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByRegistryImageAndVersion provides a mock function with given fields: ctx, registryID, image, version, softDeleteFilter
func (_m *ArtifactRepository) GetByRegistryImageAndVersion(ctx context.Context, registryID int64, image string, version string, opts ...types.QueryOption) (*types.Artifact, error) {
	ret := _m.Called(ctx, registryID, image, version, softDeleteFilter)

	if len(ret) == 0 {
		panic("no return value specified for GetByRegistryImageAndVersion")
	}

	var r0 *types.Artifact
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, types.SoftDeleteFilter) (*types.Artifact, error)); ok {
		return rf(ctx, registryID, image, version, softDeleteFilter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, types.SoftDeleteFilter) *types.Artifact); ok {
		r0 = rf(ctx, registryID, image, version, softDeleteFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Artifact)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, string, types.SoftDeleteFilter) error); ok {
		r1 = rf(ctx, registryID, image, version, softDeleteFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestArtifactMetadata provides a mock function with given fields: ctx, id, identifier, image, softDeleteFilter
func (_m *ArtifactRepository) GetLatestArtifactMetadata(ctx context.Context, id int64, identifier string, image string, opts ...types.QueryOption) (*types.ArtifactMetadata, error) {
	ret := _m.Called(ctx, id, identifier, image, softDeleteFilter)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestArtifactMetadata")
	}

	var r0 *types.ArtifactMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, types.SoftDeleteFilter) (*types.ArtifactMetadata, error)); ok {
		return rf(ctx, id, identifier, image, softDeleteFilter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, types.SoftDeleteFilter) *types.ArtifactMetadata); ok {
		r0 = rf(ctx, id, identifier, image, softDeleteFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ArtifactMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, string, types.SoftDeleteFilter) error); ok {
		r1 = rf(ctx, id, identifier, image, softDeleteFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestArtifactsByRepo provides a mock function with given fields: ctx, registryID, batchSize, artifactID
func (_m *ArtifactRepository) GetLatestArtifactsByRepo(ctx context.Context, registryID int64, batchSize int, artifactID int64) (*[]types.ArtifactMetadata, error) {
	ret := _m.Called(ctx, registryID, batchSize, artifactID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestArtifactsByRepo")
	}

	var r0 *[]types.ArtifactMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int64) (*[]types.ArtifactMetadata, error)); ok {
		return rf(ctx, registryID, batchSize, artifactID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int64) *[]types.ArtifactMetadata); ok {
		r0 = rf(ctx, registryID, batchSize, artifactID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]types.ArtifactMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, int64) error); ok {
		r1 = rf(ctx, registryID, batchSize, artifactID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestByImageID provides a mock function with given fields: ctx, imageID
func (_m *ArtifactRepository) GetLatestByImageID(ctx context.Context, imageID int64) (*types.Artifact, error) {
	ret := _m.Called(ctx, imageID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestByImageID")
	}

	var r0 *types.Artifact
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*types.Artifact, error)); ok {
		return rf(ctx, imageID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *types.Artifact); ok {
		r0 = rf(ctx, imageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Artifact)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, imageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchByImageName provides a mock function with given fields: ctx, regID, name, limit, offset, softDeleteFilter
func (_m *ArtifactRepository) SearchByImageName(ctx context.Context, regID int64, name string, limit int, offset int, opts ...types.QueryOption) (*[]types.ArtifactMetadata, error) {
	ret := _m.Called(ctx, regID, name, limit, offset, softDeleteFilter)

	if len(ret) == 0 {
		panic("no return value specified for SearchByImageName")
	}

	var r0 *[]types.ArtifactMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int, int, types.SoftDeleteFilter) (*[]types.ArtifactMetadata, error)); ok {
		return rf(ctx, regID, name, limit, offset, softDeleteFilter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int, int, types.SoftDeleteFilter) *[]types.ArtifactMetadata); ok {
		r0 = rf(ctx, regID, name, limit, offset, softDeleteFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]types.ArtifactMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, int, int, types.SoftDeleteFilter) error); ok {
		r1 = rf(ctx, regID, name, limit, offset, softDeleteFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchLatestByName provides a mock function with given fields: ctx, regID, name, limit, offset, softDeleteFilter
func (_m *ArtifactRepository) SearchLatestByName(ctx context.Context, regID int64, name string, limit int, offset int, opts ...types.QueryOption) (*[]types.Artifact, error) {
	ret := _m.Called(ctx, regID, name, limit, offset, softDeleteFilter)

	if len(ret) == 0 {
		panic("no return value specified for SearchLatestByName")
	}

	var r0 *[]types.Artifact
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int, int, types.SoftDeleteFilter) (*[]types.Artifact, error)); ok {
		return rf(ctx, regID, name, limit, offset, softDeleteFilter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int, int, types.SoftDeleteFilter) *[]types.Artifact); ok {
		r0 = rf(ctx, regID, name, limit, offset, softDeleteFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]types.Artifact)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, int, int, types.SoftDeleteFilter) error); ok {
		r1 = rf(ctx, regID, name, limit, offset, softDeleteFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Purge provides a mock function with given fields: ctx, accountID, deletedBeforeOrAt
func (_m *ArtifactRepository) Purge(ctx context.Context, accountID string, deletedBeforeOrAt int64) (int64, error) {
	ret := _m.Called(ctx, accountID, deletedBeforeOrAt)

	if len(ret) == 0 {
		panic("no return value specified for Purge")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (int64, error)); ok {
		return rf(ctx, accountID, deletedBeforeOrAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) int64); ok {
		r0 = rf(ctx, accountID, deletedBeforeOrAt)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, accountID, deletedBeforeOrAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RestoreByImageNameAndRegistryID provides a mock function with given fields: ctx, regID, image
func (_m *ArtifactRepository) RestoreByImageNameAndRegistryID(ctx context.Context, regID int64, image string) error {
	ret := _m.Called(ctx, regID, image)

	if len(ret) == 0 {
		panic("no return value specified for RestoreByImageNameAndRegistryID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, regID, image)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RestoreByVersionAndImageName provides a mock function with given fields: ctx, image, version, regID
func (_m *ArtifactRepository) RestoreByVersionAndImageName(ctx context.Context, image string, version string, regID int64) error {
	ret := _m.Called(ctx, image, version, regID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreByVersionAndImageName")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) error); ok {
		r0 = rf(ctx, image, version, regID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SoftDeleteByImageNameAndRegistryID provides a mock function with given fields: ctx, regID, image
func (_m *ArtifactRepository) SoftDeleteByImageNameAndRegistryID(ctx context.Context, regID int64, image string) error {
	ret := _m.Called(ctx, regID, image)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteByImageNameAndRegistryID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, regID, image)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SoftDeleteByVersionAndImageName provides a mock function with given fields: ctx, image, version, regID
func (_m *ArtifactRepository) SoftDeleteByVersionAndImageName(ctx context.Context, image string, version string, regID int64) error {
	ret := _m.Called(ctx, image, version, regID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteByVersionAndImageName")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) error); ok {
		r0 = rf(ctx, image, version, regID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RestoreByUUID provides a mock function with given fields: ctx, uuid
func (_m *ArtifactRepository) RestoreByUUID(ctx context.Context, uuid string) error {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for RestoreByUUID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateArtifactMetadata provides a mock function with given fields: ctx, metadata, artifactID
func (_m *ArtifactRepository) UpdateArtifactMetadata(ctx context.Context, metadata json.RawMessage, artifactID int64) error {
	ret := _m.Called(ctx, metadata, artifactID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateArtifactMetadata")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, json.RawMessage, int64) error); ok {
		r0 = rf(ctx, metadata, artifactID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewArtifactRepository creates a new instance of ArtifactRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArtifactRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArtifactRepository {
	mock := &ArtifactRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
