// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	store "github.com/harness/gitness/registry/app/store"
	types "github.com/harness/gitness/registry/types"
)

// RegistryRepository is an autogenerated mock type for the RegistryRepository type
type RegistryRepository struct {
	mock.Mock
}

// Count provides a mock function with given fields: ctx
func (_m *RegistryRepository) Count(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountAll provides a mock function with given fields: ctx, parentIDs, packageTypes, search, repoType, softDeleteFilter
func (_m *RegistryRepository) CountAll(ctx context.Context, parentIDs []int64, packageTypes []string, search string, repoType string, softDeleteFilter types.SoftDeleteFilter) (int64, error) {
	ret := _m.Called(ctx, parentIDs, packageTypes, search, repoType, softDeleteFilter)

	if len(ret) == 0 {
		panic("no return value specified for CountAll")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64, []string, string, string, types.SoftDeleteFilter) (int64, error)); ok {
		return rf(ctx, parentIDs, packageTypes, search, repoType, softDeleteFilter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64, []string, string, string, types.SoftDeleteFilter) int64); ok {
		r0 = rf(ctx, parentIDs, packageTypes, search, repoType, softDeleteFilter)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64, []string, string, string, types.SoftDeleteFilter) error); ok {
		r1 = rf(ctx, parentIDs, packageTypes, search, repoType, softDeleteFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, repository
func (_m *RegistryRepository) Create(ctx context.Context, repository *types.Registry) (int64, error) {
	ret := _m.Called(ctx, repository)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.Registry) (int64, error)); ok {
		return rf(ctx, repository)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *types.Registry) int64); ok {
		r0 = rf(ctx, repository)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *types.Registry) error); ok {
		r1 = rf(ctx, repository)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, parentID, name
func (_m *RegistryRepository) Delete(ctx context.Context, parentID int64, name string) error {
	ret := _m.Called(ctx, parentID, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, parentID, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchRegistriesIDByUpstreamProxyID provides a mock function with given fields: ctx, upstreamProxyID, rootParentID
func (_m *RegistryRepository) FetchRegistriesIDByUpstreamProxyID(ctx context.Context, upstreamProxyID string, rootParentID int64) ([]int64, error) {
	ret := _m.Called(ctx, upstreamProxyID, rootParentID)

	if len(ret) == 0 {
		panic("no return value specified for FetchRegistriesIDByUpstreamProxyID")
	}

	var r0 []int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) ([]int64, error)); ok {
		return rf(ctx, upstreamProxyID, rootParentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) []int64); ok {
		r0 = rf(ctx, upstreamProxyID, rootParentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, upstreamProxyID, rootParentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchUpstreamProxyIDs provides a mock function with given fields: ctx, repokeys, parentID
func (_m *RegistryRepository) FetchUpstreamProxyIDs(ctx context.Context, repokeys []string, parentID int64) ([]int64, error) {
	ret := _m.Called(ctx, repokeys, parentID)

	if len(ret) == 0 {
		panic("no return value specified for FetchUpstreamProxyIDs")
	}

	var r0 []int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, int64) ([]int64, error)); ok {
		return rf(ctx, repokeys, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, int64) []int64); ok {
		r0 = rf(ctx, repokeys, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, int64) error); ok {
		r1 = rf(ctx, repokeys, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchUpstreamProxyKeys provides a mock function with given fields: ctx, ids
func (_m *RegistryRepository) FetchUpstreamProxyKeys(ctx context.Context, ids []int64) ([]string, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FetchUpstreamProxyKeys")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) ([]string, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) []string); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, id, softDeleteFilter
func (_m *RegistryRepository) Get(ctx context.Context, id int64, softDeleteFilter types.SoftDeleteFilter) (*types.Registry, error) {
	ret := _m.Called(ctx, id, softDeleteFilter)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *types.Registry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, types.SoftDeleteFilter) (*types.Registry, error)); ok {
		return rf(ctx, id, softDeleteFilter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, types.SoftDeleteFilter) *types.Registry); ok {
		r0 = rf(ctx, id, softDeleteFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Registry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, types.SoftDeleteFilter) error); ok {
		r1 = rf(ctx, id, softDeleteFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx, parentIDs, packageTypes, sortByField, sortByOrder, limit, offset, search, repoType, filters
func (_m *RegistryRepository) GetAll(ctx context.Context, parentIDs []int64, packageTypes []string, sortByField string, sortByOrder string, limit int, offset int, search string, repoType string, filters *types.FilterParams) (*[]store.RegistryMetadata, error) {
	ret := _m.Called(ctx, parentIDs, packageTypes, sortByField, sortByOrder, limit, offset, search, repoType, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 *[]store.RegistryMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64, []string, string, string, int, int, string, string, *types.FilterParams) (*[]store.RegistryMetadata, error)); ok {
		return rf(ctx, parentIDs, packageTypes, sortByField, sortByOrder, limit, offset, search, repoType, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64, []string, string, string, int, int, string, string, *types.FilterParams) *[]store.RegistryMetadata); ok {
		r0 = rf(ctx, parentIDs, packageTypes, sortByField, sortByOrder, limit, offset, search, repoType, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]store.RegistryMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64, []string, string, string, int, int, string, string, *types.FilterParams) error); ok {
		r1 = rf(ctx, parentIDs, packageTypes, sortByField, sortByOrder, limit, offset, search, repoType, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIDIn provides a mock function with given fields: ctx, ids, softDeleteFilter
func (_m *RegistryRepository) GetByIDIn(ctx context.Context, ids []int64, softDeleteFilter types.SoftDeleteFilter) (*[]types.Registry, error) {
	ret := _m.Called(ctx, ids, softDeleteFilter)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDIn")
	}

	var r0 *[]types.Registry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64, types.SoftDeleteFilter) (*[]types.Registry, error)); ok {
		return rf(ctx, ids, softDeleteFilter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64, types.SoftDeleteFilter) *[]types.Registry); ok {
		r0 = rf(ctx, ids, softDeleteFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]types.Registry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64, types.SoftDeleteFilter) error); ok {
		r1 = rf(ctx, ids, softDeleteFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByParentIDAndName provides a mock function with given fields: ctx, parentID, name, includeSoftDeleted
func (_m *RegistryRepository) GetByParentIDAndName(ctx context.Context, parentID int64, name string, includeSoftDeleted types.SoftDeleteFilter) (*types.Registry, error) {
	ret := _m.Called(ctx, parentID, name, includeSoftDeleted)

	if len(ret) == 0 {
		panic("no return value specified for GetByParentIDAndName")
	}

	var r0 *types.Registry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, types.SoftDeleteFilter) (*types.Registry, error)); ok {
		return rf(ctx, parentID, name, includeSoftDeleted)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, types.SoftDeleteFilter) *types.Registry); ok {
		r0 = rf(ctx, parentID, name, includeSoftDeleted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Registry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, types.SoftDeleteFilter) error); ok {
		r1 = rf(ctx, parentID, name, includeSoftDeleted)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByRootParentIDAndName provides a mock function with given fields: ctx, parentID, name, includeSoftDeleted
func (_m *RegistryRepository) GetByRootParentIDAndName(ctx context.Context, parentID int64, name string, includeSoftDeleted types.SoftDeleteFilter) (*types.Registry, error) {
	ret := _m.Called(ctx, parentID, name, includeSoftDeleted)

	if len(ret) == 0 {
		panic("no return value specified for GetByRootParentIDAndName")
	}

	var r0 *types.Registry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, types.SoftDeleteFilter) (*types.Registry, error)); ok {
		return rf(ctx, parentID, name, includeSoftDeleted)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, types.SoftDeleteFilter) *types.Registry); ok {
		r0 = rf(ctx, parentID, name, includeSoftDeleted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Registry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, types.SoftDeleteFilter) error); ok {
		r1 = rf(ctx, parentID, name, includeSoftDeleted)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDistinctAccountIDs provides a mock function with given fields: ctx
func (_m *RegistryRepository) GetDistinctAccountIDs(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDistinctAccountIDs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Purge provides a mock function with given fields: ctx, accountID, deletedBeforeOrAt
func (_m *RegistryRepository) Purge(ctx context.Context, accountID string, deletedBeforeOrAt int64) (int64, error) {
	ret := _m.Called(ctx, accountID, deletedBeforeOrAt)

	if len(ret) == 0 {
		panic("no return value specified for Purge")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (int64, error)); ok {
		return rf(ctx, accountID, deletedBeforeOrAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) int64); ok {
		r0 = rf(ctx, accountID, deletedBeforeOrAt)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, accountID, deletedBeforeOrAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Restore provides a mock function with given fields: ctx, parentID, name
func (_m *RegistryRepository) Restore(ctx context.Context, parentID int64, name string) error {
	ret := _m.Called(ctx, parentID, name)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, parentID, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SoftDelete provides a mock function with given fields: ctx, parentID, name
func (_m *RegistryRepository) SoftDelete(ctx context.Context, parentID int64, name string) error {
	ret := _m.Called(ctx, parentID, name)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, parentID, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, repository
func (_m *RegistryRepository) Update(ctx context.Context, repository *types.Registry) error {
	ret := _m.Called(ctx, repository)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.Registry) error); ok {
		r0 = rf(ctx, repository)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRegistryRepository creates a new instance of RegistryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegistryRepository {
	mock := &RegistryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
